// ---------------------------------------------------------------------------
// Wolf AI — user-facing assistant + admin AI panel endpoints.
//   • askWolfAi  — user/VIP/admin ask the engine's AI (same provider gateway
//                  as the engine: Gemini/OpenAI/Anthropic/OpenRouter)
//   • myAiChats  — a user's recent chat history (cached in ai_analysis)
//   • testAi     — admin: live connection test for the configured provider
//   • listAiUsage — admin: usage stats + recent AI outputs
// AI never trades: it only explains/educates. The engine's rules decide trades.
// ---------------------------------------------------------------------------
import { v } from "convex/values";
import { action, internalAction, internalMutation, internalQuery, mutation, query } from "./_generated/server";
import { internal } from "./_generated/api";
import { requireAdmin, requireStaff, resolveUserInternal, resolveWolfUser } from "./wolfAuth";
import { cronThrottle, getSettingsMap, setSetting } from "./settings";
import { audit, log } from "./logs";
import { parseVerbalizedConfidence, stripConfidenceLine, verbalizedPick } from "./aiProviders";

/** Users see the last 24h of their chats; older rows are purged by cron. */
export const CHAT_TTL_MS = 24 * 3600 * 1000;

export const askWolfAi = mutation({
  args: {
    token: v.string(),
    question: v.string(),
    scope: v.optional(v.union(v.literal("advisor"), v.literal("admin"))),
    provider: v.optional(v.string()),
    model: v.optional(v.string()),
    image: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const user = await resolveWolfUser(ctx, args.token);
    if (!user) throw new Error("session_expired");
    const question = args.question.trim().slice(0, 2000);
    if (!question) throw new Error("سؤال خالی است");
    const settings = await getSettingsMap(ctx);
    if (settings["ai.enabled"] === false) throw new Error("هوش مصنوعی موقتاً غیرفعال است");
    // A user's own AI preference (set in the profile → entertainment tab)
    // overrides the admin default for their chats. The robust chain still
    // falls back automatically, so a bad preference never breaks the answer.
    const userProvider = String((user as any).aiProvider ?? "").trim();
    const userModel = String((user as any).aiModel ?? "").trim();
    // "auto" and "random" are meta-values, not real providers:
    //   • auto   → follow the admin default (which may itself be random mode)
    //   • random → each answer is generated by a RANDOM available AI
    const explicit = userProvider && userProvider !== "auto" ? userProvider : "";
    const wantRandom = explicit === "random";
    const provider = wantRandom || !explicit ? String(settings["ai.provider"] ?? "gemini") : explicit;
    const model = userModel || String(settings["ai.model"] ?? "gemini-2.5-flash");
    // Random mode is the default (ai.randomProvider=true): the actual provider
    // that answered is stored on the result and shown under each reply, so the
    // selection is never fake — it either picks that AI or visibly falls back.
    const random = wantRandom || (!explicit && settings["ai.randomProvider"] !== false);
    const selfVerify = settings["ai.selfVerify"] === true;
    const aiKey = String(settings["ai.key"] ?? "");
    const freeFallback = !(settings["ai.freeFallback"] === false || settings["ai.freeFallback"] === "false");
    // Users get the free-provider chain too: no key configured in the panel is
    // OK when free fallback is on (env keys from the Keys tab are used).
    if (!aiKey && !freeFallback) throw new Error("هوش مصنوعی هنوز در تنظیمات مدیر پیکربندی نشده است");
    const sys = String(settings["ai.systemPrompt"] ?? "");
    const now = Date.now();
    const key = `chat:${user._id}:${now}`;

    // Wolf-coin cost per question (admin-configurable, 0 = free).
    // Charged up-front; refunded automatically if the AI call errors.
    const isAdmin = Boolean((user as any).isAdmin) || (user as any).role === "admin";
    // Admins use every AI feature with NO limits (no wolf-coin cost, explicit
    // provider/model override). Regular users pay wolf coins per question.
    const aiCost = isAdmin ? 0 : Math.max(0, Math.floor(Number(settings["coins.aiCost"] ?? 50)));
    if (aiCost > 0) {
      const balance = (user as any).wolfCoins ?? 0;
      if (balance < aiCost) {
        throw new Error(`برای هر سؤال از مشاور هوش مصنوعی ${aiCost} سکه ولف لازم است — موجودی فعلی شما ${balance} سکه است`);
      }
      const next = balance - aiCost;
      await ctx.db.patch(user._id as any, { wolfCoins: next });
      await ctx.db.insert("coinTransactions", {
        userId: user._id as any,
        currency: "wolf",
        delta: -aiCost,
        balanceAfter: next,
        reason: "ai_chat",
        ref: key,
        created: now,
      });
    }
    // Admin can pin the exact provider/model for a chat ("با کدوم حرف بزنم");
    // regular users keep their own preference or the rotating chain.
    const overrideProvider = isAdmin && args.provider ? String(args.provider).trim() : "";
    const overrideModel = isAdmin && args.model ? String(args.model).trim() : "";
    const finalProvider = overrideProvider || provider;
    const finalModel = overrideModel || model;
    const prompt =
      args.scope === "admin"
        ? `[Admin context] ${question}`
        : `The user asks about trading on Trading Wolf AI. Answer in Persian (فارسی) unless they write in English. Keep it concise, practical and educational — explain strategies, risk, and how the engine works, but never promise profits.\n\nQuestion: ${question}`;
    await ctx.db.insert("ai_analysis", {
      kind: "chat",
      key,
      provider: finalProvider,
      model: finalModel,
      text: "",
      status: "running",
      created: now,
    });
    await ctx.scheduler.runAfter(0, internal.aiChat.runGenerate, {
      key,
      provider: finalProvider,
      model: finalModel,
      aiKey,
      freeFallback,
      random,
      selfVerify,
      system: sys || "You are WOLF AI, the assistant of Trading Wolf AI.",
      prompt,
      image: args.image && args.image.startsWith("data:image/") ? args.image.slice(0, 7_000_000) : undefined,
    });
    await log(ctx, "AI", "ai.chat.asked", `user=${user.username} scope=${args.scope ?? "advisor"}`, "ai");
    return { id: key, ok: true };
  },
});

export const runGenerate = internalAction({
  args: {
    key: v.string(),
    provider: v.string(),
    model: v.string(),
    aiKey: v.string(),
    freeFallback: v.optional(v.boolean()),
    random: v.optional(v.boolean()),
    selfVerify: v.optional(v.boolean()),
    system: v.string(),
    prompt: v.string(),
    image: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    try {
      // Robust call: in random mode the answer comes from a RANDOM available
      // provider; otherwise the configured provider first, then the free
      // chain. Users always have an advisor even when the panel key is bad.
      const robustArgs = {
        provider: args.provider,
        model: args.model,
        key: args.aiKey,
        freeFallback: args.freeFallback !== false,
        random: args.random === true,
        system: args.system,
        prompt: args.prompt,
        image: args.image,
      } as const;
      const res = (await ctx.runAction(internal.nodeCalls.aiGenerateRobust, robustArgs)) as {
        ok?: boolean;
        text?: string;
        provider?: string;
      };
      let text = String(res?.text ?? "").trim();
      let usedProvider = String(res?.provider ?? args.provider);
      // Verbalized sampling (CHATS-lab/verbalized-sampling essence): take a
      // second sample with a verbalized-confidence instruction and keep the
      // most-confident answer (self-consistency). Never breaks the answer —
      // if the second sample fails, the first one stands.
      if (args.selfVerify === true && res?.ok && text) {
        try {
          const res2 = (await ctx.runAction(internal.nodeCalls.aiGenerateRobust, {
            ...robustArgs,
            system: `${args.system}\n\nAnswer the question, then on the very last line write exactly: Confidence: <0-100>`,
          })) as { ok?: boolean; text?: string; provider?: string };
          const t2 = String(res2?.text ?? "").trim();
          if (t2) {
            const chosen = verbalizedPick([
              { text, confidence: parseVerbalizedConfidence(text) },
              { text: t2, confidence: parseVerbalizedConfidence(t2) },
            ]);
            if (chosen) {
              text = stripConfidenceLine(chosen);
              usedProvider = String(res2?.provider ?? usedProvider);
            }
          }
        } catch {
          // sampling must never break the answer — keep the first sample
        }
      }
      await ctx.runMutation(internal.aiChat.storeResult, {
        key: args.key,
        text: text || "بدون پاسخ",
        status: "done",
        provider: usedProvider,
        model: args.model,
        error: "",
      });
    } catch (e: any) {
      await ctx.runMutation(internal.aiChat.storeResult, {
        key: args.key,
        text: "",
        status: "error",
        provider: args.provider,
        model: args.model,
        error: String(e?.message ?? "ai_error").slice(0, 500),
      });
    }
  },
});

export const storeResult = internalMutation({
  args: {
    key: v.string(),
    text: v.string(),
    status: v.string(),
    provider: v.string(),
    model: v.string(),
    error: v.string(),
  },
  handler: async (ctx, args) => {
    // Refund the wolf-coin cost when the AI call failed — the user paid for
    // an answer they never received.
    if (args.status === "error" && String(args.key ?? "").startsWith("chat:")) {
      const parts = String(args.key).split(":");
      const userId = parts[1];
      if (userId) {
        try {
          const u = await ctx.db.get(userId as any);
          if (u) {
            const settings = await getSettingsMap(ctx);
            const cost = Math.max(0, Math.floor(Number(settings["coins.aiCost"] ?? 50)));
            if (cost > 0) {
              const next = ((u as any).wolfCoins ?? 0) + cost;
              await ctx.db.patch(u._id as any, { wolfCoins: next });
              await ctx.db.insert("coinTransactions", {
                userId: u._id as any,
                currency: "wolf",
                delta: cost,
                balanceAfter: next,
                reason: "ai_refund",
                ref: args.key,
                created: Date.now(),
              });
            }
          }
        } catch {
          // refund must never break storing the AI result
        }
      }
    }

    const rows = await ctx.db.query("ai_analysis").withIndex("by_kind", (q: any) => q.eq("kind", "chat")).collect();
    const row = rows.find((r: any) => r.key === args.key);
    if (!row) {
      await ctx.db.insert("ai_analysis", {
        kind: "chat",
        key: args.key,
        provider: args.provider,
        model: args.model,
        text: args.text,
        status: args.status as "done" | "error",
        error: args.error || undefined,
        created: Date.now(),
      });
      return;
    }
    await ctx.db.patch(row._id, {
      text: args.text,
      status: args.status as "done" | "error",
      error: args.error || undefined,
      // Store the provider/model that ACTUALLY answered (not just the one
      // selected) so the UI shows which AI produced the reply.
      provider: args.provider,
      model: args.model,
    });
  },
});

/**
 * Text-to-speech for WOLF AI replies via the self-hosted openai-edge-tts
 * server (OpenAI-compatible /v1/audio/speech). Returns base64 MP3.
 * Requires tts.enabled (admin setting); the base URL / voice / speed come
 * from the same settings block. The optional apiKey is only sent when set
 * (server REQUIRE_API_KEY=True).
 */
/** Action-safe settings read (actions have no ctx.db — getSettingsMap crashes). */
async function actionSettings(ctx: any): Promise<Record<string, any>> {
  return (await ctx.runQuery(internal.settings.rawSettings, {})) as Record<string, any>;
}

export const speakText = action({
  args: { token: v.string(), text: v.string() },
  handler: async (ctx, args) => {
    // Actions have no ctx.db — resolve through the internal query wrapper.
    const user = await ctx.runQuery(internal.wolfAuth.resolveUserInternal, {
      token: args.token,
    });
    if (!user) throw new Error("session_expired");
    const settings = await actionSettings(ctx);
    const enabled = settings["tts.enabled"];
    if (enabled === false || enabled === "false") throw new Error("tts_disabled");
    const text = String(args.text ?? "").trim().slice(0, 4000);
    if (!text) throw new Error("متن خالی است");
    // Language-aware voice: English users hear an English voice even if the
    // stored tts.voice is the Persian default; Persian users keep the admin's
    // voice setting (default fa-IR-FaridNeural).
    const userLang = String((user as any).language ?? "fa") === "en" ? "en" : "fa";
    const storedVoice = String(settings["tts.voice"] ?? "").trim();
    const voice =
      userLang === "en" ? "en-US-AvaNeural" : storedVoice || "fa-IR-FaridNeural";
    const r = (await ctx.runAction(internal.nodeCalls.edgeTtsSpeak, {
      text,
      baseUrl: String(settings["tts.baseUrl"] ?? ""),
      voice,
      speed: Number(settings["tts.speed"] ?? 1),
      apiKey: String(settings["tts.apiKey"] ?? ""),
    })) as { ok?: boolean; audioBase64?: string; format?: string; bytes?: number };
    if (!r?.ok || !r.audioBase64) throw new Error("tts_failed");
    return r;
  },
});

export const myAiChats = query({
  args: { token: v.string() },
  handler: async (ctx, { token }) => {
    const user = await resolveWolfUser(ctx, token);
    if (!user) return [];
    // Only the last 24h — history expires automatically (purged by cron).
    const cutoff = Date.now() - CHAT_TTL_MS;
    const rows = await ctx.db.query("ai_analysis").withIndex("by_kind", (q: any) => q.eq("kind", "chat")).order("desc").take(100);
    return rows
      .filter((r: any) => String(r.key ?? "").startsWith(`chat:${user._id}:`) && (r.created ?? 0) >= cutoff)
      .slice(0, 50)
      .map((r: any) => ({
        id: r._id,
        key: r.key,
        text: r.text,
        status: r.status,
        error: r.error,
        provider: r.provider,
        created: r.created,
      }));
  },
});

/** Cron: drop user chat rows older than 24h (history expires, DB stays small). */
export const pruneChatHistory = internalMutation({
  args: {},
  handler: async (ctx) => {
    const settings = await getSettingsMap(ctx);
    const hours = Math.max(1, Number(settings["chat.purgeHours"] ?? 6) || 6);
    const due = await cronThrottle(ctx, "chat.lastPurgeAt", hours * 60);
    if (!due) return { ok: true, skipped: true, deleted: 0 };
    const cutoff = Date.now() - CHAT_TTL_MS;
    const rows = await ctx.db.query("ai_analysis").withIndex("by_kind", (q: any) => q.eq("kind", "chat")).collect();
    let deleted = 0;
    for (const r of rows) {
      if ((r.created ?? 0) < cutoff) {
        await ctx.db.delete(r._id);
        deleted++;
      }
    }
    return { ok: true, deleted };
  },
});

/**
 * Internal: tuning context for the AI learning supervisor — current gates,
 * per-strategy performance, recent closed trades and the known strategy keys
 * (so AI-suggested weights are validated before being applied).
 */
export const learningTuningContext = internalQuery({
  args: {},
  handler: async (ctx) => {
    const settings = await getSettingsMap(ctx);
    const perf = await ctx.db.query("strategyPerformance").collect();
    const weekAgo = Date.now() - 7 * 86400000;
    const closed = await ctx.db
      .query("closed_positions")
      .withIndex("by_time", (q: any) => q.gte("closeTime", weekAgo))
      .order("desc")
      .take(60);
    const knownKeys = (await ctx.db.query("strategies").collect()).map((s: any) => s.key);
    return {
      current: {
        minScore: Number(settings["risk.minScore"] ?? 35),
        minConfidence: Number(settings["risk.minConfidence"] ?? 0.5),
        minConsensus: Number(settings["risk.minConsensus"] ?? 0.55),
        minConfirmations: Number(settings["risk.minConfirmations"] ?? 3),
        minRR: Number(settings["risk.minRR"] ?? 1.0),
      },
      autoApply:
        settings["learning.autoApply"] === true || settings["learning.autoApply"] === "true",
      perf: perf
        .sort((a: any, b: any) => (b.totalPnl ?? 0) - (a.totalPnl ?? 0))
        .slice(0, 15)
        .map((r: any) => ({
          key: r.strategyKey,
          trades: r.trades,
          wins: r.wins,
          winRate: r.winRate,
          totalPnl: r.totalPnl,
        })),
      closed: closed.map((p: any) => ({
        symbol: p.symbol,
        side: p.side,
        strategies: p.strategyKeys ?? [],
        profit: Number(p.profit ?? 0).toFixed(4),
        reason: p.closeReason,
      })),
      knownKeys,
    };
  },
});

/** Internal: apply a bounded engine-gate adjustment learned from the AI. */
export const applyTuning = internalMutation({
  args: { key: v.string(), value: v.number() },
  handler: async (ctx, { key, value }) => {
    await setSetting(ctx, key, value, "ai-learning");
  },
});

/** Internal: apply an AI-suggested strategy weight (validated, bounded). */
export const applyStrategyWeight = internalMutation({
  args: { key: v.string(), weight: v.number() },
  handler: async (ctx, { key, weight }) => {
    const row = await ctx.db
      .query("strategies")
      .filter((q: any) => q.eq(q.field("key"), key))
      .first();
    if (row) await ctx.db.patch(row._id, { weight: Number(weight) });
  },
});

/**
 * AI review of the engine's learning (cron every 6h): takes the top recent
 * learningHistory rows + per-strategy performance and produces a bilingual
 * assessment. When learning.autoApply is on, the AI's bounded gate/weight
 * suggestions are APPLIED (clamped to safe floors) — the engine genuinely
 * learns from experience and from the AI daily, not just stores rows.
 */
export const aiReviewLearning = internalAction({
  args: {},
  handler: async (ctx) => {
    try {
      const settings = await actionSettings(ctx);
      const hours = Math.max(1, Number(settings["ai.learningReviewHours"] ?? 6) || 6);
      const due = (await ctx.runMutation(internal.settings.tickCron, {
        lastKey: "ai.lastLearningReviewAt",
        minutes: hours * 60,
      })) as boolean;
      if (!due) return { ok: true, skipped: true, reviewed: 0 };
      const dayStart = Date.now() - 24 * 3600 * 1000;
      const rows: any[] = (await ctx.runQuery(internal.engineData.recentLearning, {
        after: dayStart,
        limit: 8,
      })) as any[];
      const tuning = (await ctx.runQuery(internal.aiChat.learningTuningContext, {})) as any;
      const items: any[] = (rows ?? []).map((r: any) => ({
        symbol: r.symbol,
        signal: r.signal,
        scores: r.scores,
        win: r.win,
        lesson: String(r.lesson ?? "").slice(0, 200),
      }));
      if (items.length === 0 && (tuning?.perf ?? []).length === 0) {
        return { ok: true, reviewed: 0 };
      }
      const perfLine =
        (tuning?.perf ?? [])
          .slice(0, 6)
          .map((r: any) => `${r.key}: ${r.trades}t ${r.winRate}% win ${r.totalPnl}$`)
          .join(" | ") || "no strategy data yet";
      const prompt =
        `You are the learning supervisor of the WOLF trading engine. Below are the engine's recent learning entries and per-strategy performance. ` +
        `Assess what the engine is learning well and what mistake it keeps repeating. Then, using ONLY the data provided, propose small tuning changes: ` +
        `{"minScore":<20-50>,"minConfidence":<0.40-0.65>,"minConsensus":<0.40-0.60>,"minConfirmations":<2-4>,"minRR":<0.8-1.5>} ` +
        `and optional strategyWeights [{"key":"<strategy_key>","weight":<0.3-1.5>}] (max 5, only for strategies you are confident about). ` +
        `Raise gates when many losses came from weak setups; lower them only slightly when nothing traded for a long time. ` +
        `Respond in strict JSON only: {"assessmentFa":"...","assessmentEn":"...","adjustments":{...},"strategyWeights":[...]}. ` +
        `Under 150 words total.\n\nCurrent gates: ${JSON.stringify(tuning?.current ?? {})}\n\nPer-strategy performance:\n${perfLine}\n\nRecent entries:\n` +
        JSON.stringify(items);
      const res = (await ctx.runAction(internal.nodeCalls.aiGenerateRobust, {
        provider: String(settings["ai.provider"] ?? "pollinations"),
        system:
          "You are the WOLF AI learning supervisor. You only make small, safe, data-driven tuning changes — never reckless ones.",
        prompt,
      })) as { ok?: boolean; text?: string; provider?: string };
      const text = String(res?.text ?? "").trim();
      if (!text) return { ok: false, reviewed: 0 };

      // ── bounded auto-apply of the AI's suggestions ────────────────────
      const applied: string[] = [];
      if (tuning?.autoApply) {
        const m = text.match(/\{[\s\S]*\}/);
        let parsed: any = {};
        if (m) {
          try {
            parsed = JSON.parse(m[0]);
          } catch {
            parsed = {};
          }
        }
        const adjustments: Record<string, number> = parsed.adjustments ?? {};
        const bounds: Record<string, [number, number, number]> = {
          "risk.minScore": [20, 50, 1],
          "risk.minConfidence": [0.4, 0.65, 0.05],
          "risk.minConsensus": [0.4, 0.6, 0.05],
          "risk.minConfirmations": [2, 4, 1],
          "risk.minRR": [0.8, 1.5, 0.1],
        };
        const curMap: Record<string, number> = {
          "risk.minScore": Number(tuning.current?.minScore ?? 35),
          "risk.minConfidence": Number(tuning.current?.minConfidence ?? 0.5),
          "risk.minConsensus": Number(tuning.current?.minConsensus ?? 0.55),
          "risk.minConfirmations": Number(tuning.current?.minConfirmations ?? 3),
          "risk.minRR": Number(tuning.current?.minRR ?? 1.0),
        };
        for (const [k, [lo, hi, step]] of Object.entries(bounds)) {
          const raw = Number(adjustments[k.replace("risk.", "")] ?? adjustments[k]);
          if (!Number.isFinite(raw)) continue;
          const val = Number(Math.min(hi, Math.max(lo, Math.round(raw / step) * step)).toFixed(3));
          if (Math.abs(val - curMap[k]) >= step) {
            await ctx.runMutation(internal.aiChat.applyTuning, { key: k, value: val });
            applied.push(`${k}: ${curMap[k]} → ${val}`);
          }
        }
        const known = new Set(tuning.knownKeys ?? []);
        const weights: Array<{ key?: string; weight?: number }> = Array.isArray(parsed.strategyWeights)
          ? parsed.strategyWeights
          : [];
        for (const w of weights.slice(0, 5)) {
          const key = String(w.key ?? "");
          const raw = Number(w.weight);
          if (!known.has(key) || !Number.isFinite(raw)) continue;
          const val = Number(Math.min(1.5, Math.max(0.3, raw)).toFixed(3));
          await ctx.runMutation(internal.aiChat.applyStrategyWeight, { key, weight: val });
          applied.push(`weight:${key} → ${val}`);
        }
      }
      const suffix = applied.length > 0 ? `\n\n🔧 Applied (auto-learn): ${applied.join(", ")}` : "";
      await ctx.runMutation(internal.aiChat.storeResult, {
        key: `learning_review:${Date.now()}`,
        text: text.slice(0, 3900) + suffix,
        status: "done",
        provider: String(res?.provider ?? "pollinations"),
        model: "",
        error: "",
      });
      if (applied.length > 0) {
        await log(ctx, "LEARNING", "ai.learning.applied", applied.join(" | "), "engine");
      }
      return { ok: true, reviewed: items.length, applied: applied.length };
    } catch (e: any) {
      console.warn(`[ai] learning review failed: ${e?.message ?? e}`);
      return { ok: false, error: String(e?.message ?? e).slice(0, 200) };
    }
  },
});

/**
 * AI proposes NEW trading strategies (from its broad market knowledge = the
 * "internet" layer). Results are stored as kind "strategy_suggest" for the
 * admin to review in the AI center — the deterministic evaluator is never
 * modified at runtime.
 */
export const suggestStrategies = mutation({
  args: { token: v.string(), focus: v.optional(v.string()) },
  handler: async (ctx, { token, focus }) => {
    const admin = await requireAdmin(ctx, token);
    const settings = await getSettingsMap(ctx);
    if (settings["ai.researchEnabled"] === false) {
      throw new Error("تحقیق هوش مصنوعی در تنظیمات غیرفعال است");
    }
    const key = `strategy_suggest:${Date.now()}`;
    await ctx.db.insert("ai_analysis", {
      kind: "strategy_suggest",
      key,
      provider: "ai",
      model: "",
      text: "",
      status: "running",
      created: Date.now(),
    });
    const prompt =
      `You are a professional quant strategist. Propose 3 NEW, concrete, actionable trading strategies that are NOT obvious duplicates of classic EMA/RSI/MACD setups. ` +
      `Focus: ${focus || "crypto + forex, 15m-4h, both sides"}. For each: give a stable key (lowercase_snake), an English name, a Persian name, a family ` +
      `(price_action | chart_patterns | trend_following | momentum | mean_reversion | breakout | scalping | swing | smc | ict | volume | volatility | support_resistance | multi_timeframe | market_structure | liquidity | indicator_combos), the timeframes, the exact entry/exit/stop conditions, and a 0-100 risk level. ` +
      `Answer as JSON array only: [{"key":"","nameEn":"","nameFa":"","family":"","timeframes":"","entry":"","exit":"","stop":"","risk":0}]`;
    await ctx.scheduler.runAfter(0, internal.aiChat.runSuggest, { key, prompt });
    await audit(ctx, "ai.strategy_suggest", admin.username, admin._id, "ai", focus ?? "");
    return { ok: true, key };
  },
});

export const runSuggest = internalAction({
  args: { key: v.string(), prompt: v.string() },
  handler: async (ctx, args) => {
    try {
      const settings = await actionSettings(ctx);
      const res = (await ctx.runAction(internal.nodeCalls.aiGenerateRobust, {
        provider: String(settings["ai.provider"] ?? "pollinations"),
        system: "You are the WOLF AI strategy researcher. Return ONLY valid JSON.",
        prompt: args.prompt,
      })) as { ok?: boolean; text?: string; provider?: string };
      await ctx.runMutation(internal.aiChat.storeResult, {
        key: args.key,
        text: String(res?.text ?? "بدون پاسخ").slice(0, 4000),
        status: "done",
        provider: String(res?.provider ?? "ai"),
        model: "",
        error: "",
      });
    } catch (e: any) {
      await ctx.runMutation(internal.aiChat.storeResult, {
        key: args.key,
        text: "",
        status: "error",
        provider: "ai",
        model: "",
        error: String(e?.message ?? "ai_error").slice(0, 500),
      });
    }
  },
});

export const testAi = mutation({
  args: { token: v.string() },
  handler: async (ctx, { token }) => {
    const admin = await requireAdmin(ctx, token);
    const settings = await getSettingsMap(ctx);
    const provider = String(settings["ai.provider"] ?? "gemini");
    const model = String(settings["ai.model"] ?? "gemini-2.5-flash");
    const aiKey = String(settings["ai.key"] ?? "");
    // Keyless free base (Pollinations) means the test can run with NO key;
    // configured keys are used as supplements by the robust chain.
    const key = `test:${Date.now()}`;
    await ctx.scheduler.runAfter(0, internal.aiChat.runGenerate, {
      key,
      provider,
      model,
      aiKey,
      system: "Reply with exactly: OK",
      prompt: "ping",
    });
    await audit(ctx, "ai.tested", admin.username, admin._id, provider, "connection test");
    return { ok: true, message: "در حال بررسی اتصال… (نتیجه در گزارش هوش مصنوعی ظاهر می‌شود)", testKey: key };
  },
});

export const listAiUsage = query({
  args: { token: v.string() },
  handler: async (ctx, { token }) => {
    await requireStaff(ctx, token);
    const rows = await ctx.db.query("ai_analysis").order("desc").take(200);
    const byKind = new Map<string, number>();
    const byProvider = new Map<string, number>();
    let errors = 0;
    // Resolve chat ownership: chat rows have key `chat:<userId>:<ts>` — show
    // the username next to each entry so the admin knows who used the AI.
    const userIds = new Set<string>();
    for (const r of rows) {
      const m = String(r.key ?? "").match(/^chat:([^:]+):/);
      if (m) userIds.add(m[1]);
    }
    const userNames = new Map<string, string>();
    for (const uid of userIds) {
      try {
        const u = await ctx.db.get(uid as any);
        if (u) userNames.set(uid, String((u as any).username ?? (u as any).name ?? String((u as any)._id ?? uid)).slice(-24));
      } catch {
        // orphaned chat rows — no user
      }
    }
    for (const r of rows) {
      byKind.set(r.kind, (byKind.get(r.kind) ?? 0) + 1);
      byProvider.set(r.provider, (byProvider.get(r.provider) ?? 0) + 1);
      if (r.status === "error") errors++;
    }
    return {
      total: rows.length,
      errors,
      byKind: Object.fromEntries(byKind),
      byProvider: Object.fromEntries(byProvider),
      recent: rows.slice(0, 30).map((r) => {
        const m = String(r.key ?? "").match(/^chat:([^:]+):/);
        return {
          id: r._id,
          kind: r.kind,
          provider: r.provider,
          status: r.status,
          text: (r.text ?? "").slice(0, 300),
          error: r.error,
          created: r.created,
          user: m ? (userNames.get(m[1]) ?? m[1]) : undefined,
        };
      }),
    };
  },
});

/**
 * Admin: wipe AI history (chats + reviews). Deleting here removes the rows
 * from the USER panel too (same table) — exactly what the user asked: admin
 * deletes → user history is gone. Optionally filter by kind.
 */
export const clearAiHistory = mutation({
  args: { token: v.string(), kind: v.optional(v.string()) },
  handler: async (ctx, { token, kind }) => {
    const admin = await requireAdmin(ctx, token);
    const rows = await ctx.db.query("ai_analysis").collect();
    let deleted = 0;
    for (const r of rows) {
      if (kind && r.kind !== kind) continue;
      await ctx.db.delete(r._id);
      deleted++;
    }
    await audit(ctx, "ai.history_cleared", admin.username, admin._id, "ai", `${kind ?? "all"} x${deleted}`);
    return { ok: true, deleted };
  },
});

/** Admin: delete specific AI rows by id (per-entry cleanup in the AI center). */
export const deleteAiRows = mutation({
  args: { token: v.string(), ids: v.array(v.id("ai_analysis")) },
  handler: async (ctx, { token, ids }) => {
    const admin = await requireAdmin(ctx, token);
    let deleted = 0;
    for (const id of ids.slice(0, 50)) {
      await ctx.db.delete(id);
      deleted++;
    }
    await audit(ctx, "ai.history_deleted", admin.username, admin._id, "ai", `rows x${deleted}`);
    return { ok: true, deleted };
  },
});
