// ---------------------------------------------------------------------------
// WOLF Strategy Registry — data file. 100+ real, well-known trading
// strategies across the 17 standard categories. The deterministic engine
// evaluator (engineCore.ts) implements each `family`; every entry is a
// first-class DB row (enable/disable/weight from the admin panel).
// ---------------------------------------------------------------------------

export type FamilyId = string;

// Family meta: default rules text (fa) + chart overlays + default params
export const FAMILY_META: Record<string, { fa: string; overlay: string[]; rr: number }> = {
  pa_pinbar: { fa: "ورود با شمع پین‌بار در سطح معتبر (حمایت/مقاومت یا انتهای روند)", overlay: ["pinbar"], rr: 2 },
  pa_engulfing: { fa: "ورود با شمع انگالفینگ در پایان روند یا پشت سطح", overlay: ["engulfing"], rr: 1.8 },
  pa_inside: { fa: "ورود با شکست محدوده شمع مادر (Inside Bar)", overlay: ["insidebar"], rr: 2 },
  pa_fakey: { fa: "ورود پس از شکست جعلی (Fakey) در سطح کلیدی", overlay: ["fakey"], rr: 1.8 },
  pa_hammershooting: { fa: "ورود با شمع چکش/ستاره دنباله‌دار در انتهای روند", overlay: ["candle"], rr: 2 },
  pa_doji: { fa: "ورود با داوجی در انتهای حرکت و تأیید شمع بعد", overlay: ["candle"], rr: 1.8 },
  pa_threeb: { fa: "ورود با الگوی سه‌شمع (Three Bar) پس از تثبیت", overlay: ["candle"], rr: 2 },
  pat_double: { fa: "ورود با شکست گردن سقف/کف دوگانه", overlay: ["pattern"], rr: 2 },
  pat_headshoulder: { fa: "ورود با شکست خط گردن الگوی سر و شانه", overlay: ["pattern"], rr: 2.5 },
  pat_triangle: { fa: "ورود با شکست مثلث (همگرا) همراه حجم", overlay: ["triangle"], rr: 2 },
  pat_wedge: { fa: "ورود با شکست گاوه (Wedge)", overlay: ["wedge"], rr: 2 },
  pat_rectangle: { fa: "ورود با شکست محدوده مستطیل", overlay: ["rectangle"], rr: 1.8 },
  pat_flag: { fa: "ورود با شکست پرچم/پنانت در ادامه روند", overlay: ["pattern"], rr: 2 },
  pat_cup: { fa: "ورود با شکست گردن الگوی جام و دسته", overlay: ["pattern"], rr: 2.2 },
  trend_ema: { fa: "ورود در پولبک قیمت به میانگین متحرک در روند", overlay: ["ema"], rr: 2.2 },
  trend_cross: { fa: "ورود با تقاطع میانگین‌های متحرک هم‌سو با روند", overlay: ["ema"], rr: 2 },
  trend_macd: { fa: "ورود با برگشت MACD در جهت روند اصلی", overlay: ["macd"], rr: 2 },
  trend_supertrend: { fa: "ورود با تغییر جهت سوپرترند", overlay: ["supertrend"], rr: 1.8 },
  trend_adx: { fa: "ورود وقتی ADX قوی (۲۵+) جهت روند را تأیید کند", overlay: ["adx"], rr: 2 },
  trend_psar: { fa: "ورود با تغییر نقطه پارابولیک سار", overlay: ["psar"], rr: 1.8 },
  trend_channel: { fa: "ورود از محدوده پایینی/بالایی کانال روند", overlay: ["channel"], rr: 2 },
  mom_rsi: { fa: "ورود با الگوی RSI (واگرایی یا شکست 50)", overlay: ["rsi"], rr: 1.8 },
  mom_stoch: { fa: "ورود با تقاطع استوکاستیک در ناحیه اشباع", overlay: ["stoch"], rr: 1.8 },
  mom_macdhist: { fa: "ورود با رشد هیستوگرام MACD در جهت حرکت", overlay: ["macd"], rr: 2 },
  mom_roc: { fa: "ورود با شتاب مثبت/منفی ROC", overlay: ["roc"], rr: 1.8 },
  mom_cci: { fa: "ورود وقتی CCI از آستانه عبور کند", overlay: ["cci"], rr: 1.8 },
  mom_williams: { fa: "ورود با واگرایی ویلیامز %R", overlay: ["williams"], rr: 1.5 },
  meanr_bb: { fa: "ورود با لمس باند بیرونی بولینجر در روند جانبی", overlay: ["bollinger"], rr: 2 },
  meanr_rsi2: { fa: "ورود با اشباع خرید/فروش RSI کوتاه", overlay: ["rsi"], rr: 2 },
  meanr_zscore: { fa: "ورود با Z-Score دور از میانگین", overlay: ["bollinger"], rr: 2 },
  meanr_keltner: { fa: "ورود با لمس باند کلتنر در بازار رنج", overlay: ["keltner"], rr: 1.8 },
  meanr_gaps: { fa: "ورود جهت پرشدن گپ بازار", overlay: ["gap"], rr: 1.5 },
  brk_consolidation: { fa: "ورود با شکست فشردگی (Consolidation) همراه حجم", overlay: ["range"], rr: 2 },
  brk_donchian: { fa: "ورود با شکست خروجی دونچیان (حداکثر/min)", overlay: ["donchian"], rr: 2.2 },
  brk_range: { fa: "ورود با شکست بازه اولیه (Opening Range)", overlay: ["range"], rr: 1.8 },
  brk_level: { fa: "ورود با شکست سطح کلیدی + تأیید", overlay: ["level"], rr: 2 },
  brk_volatility: { fa: "ورود با شکست دوره فشردگی نوسان", overlay: ["volatility"], rr: 2 },
  brk_move: { fa: "ورود با حرکت شتابی (برک‌اوت مومنتوم)", overlay: [], rr: 1.8 },
  scalp_snr: { fa: "اسکالپ سریع از سطح حمایت/مقاومت", overlay: ["level"], rr: 1.2 },
  scalp_1m: { fa: "اسکالپ روی تایم‌فریم یک‌دقیقه‌ای با خروج سریع", overlay: [], rr: 1.2 },
  scalp_vwap: { fa: "اسکالپ برگشت/شکست VWAP", overlay: ["vwap"], rr: 1.5 },
  scalp_momentum: { fa: "اسکالپ هم‌جهت مومنتوم قوی", overlay: [], rr: 1.2 },
  swing_retest: { fa: "ورود با برک سطح و ری‌تست (Boom & Retest)", overlay: ["level"], rr: 2.5 },
  swing_aroon: { fa: "ورود با سیگنال آرون", overlay: ["aroon"], rr: 2 },
  swing_harami: { fa: "ورود با هارامی در انتهای روند", overlay: ["candle"], rr: 2 },
  swing_pullback: { fa: "ورود با پولبک به ساختار در روند سوینگ", overlay: ["ema"], rr: 2.5 },
  smc_ob: { fa: "ورود از آخرین Order Block معتبر", overlay: ["orderblock"], rr: 2.5 },
  smc_fvg: { fa: "ورود از محدود نارضبندی Fair Value Gap", overlay: ["fvg"], rr: 2.2 },
  smc_liquidity: { fa: "ورود پس از Sweep نقدینگی پشت سطح", overlay: ["liquidity"], rr: 2.5 },
  smc_mitigation: { fa: "ورود در Mitigation ناحیه برندل پس از برداشت نقدینگی", overlay: ["orderblock"], rr: 2.2 },
  smc_imbalance: { fa: "ورود با ایمبالانس در جهت روند", overlay: ["fvg"], rr: 2 },
  smc_breaker: { fa: "ورود از بریکر بلاک پس از تغییر ساختار", overlay: ["orderblock"], rr: 2.2 },
  ict_killzone: { fa: "ورود در Kill Zone با نقدینگی جمع‌شده", overlay: ["killzone"], rr: 2.2 },
  ict_opening: { fa: "ورود با شکست Opening Range", overlay: ["range"], rr: 1.8 },
  ict_ote: { fa: "ورود در ناحیه OTE (61.8–79%)", overlay: ["fib"], rr: 2.2 },
  ict_silverbullet: { fa: "ورود در Silver Bullet (ساعت طلایی لندن/NY)", overlay: ["killzone"], rr: 2 },
  ict_power3: { fa: "ورود با پترن Power of 3 (توزیع-غرایبر-توزیع مجدد)", overlay: ["level"], rr: 2 },
  ict_smart: { fa: "ورود با Smart Money Trap پس از تله", overlay: ["level"], rr: 2.2 },
  ict_judas: { fa: "ورود بر اساس Judas Swing ابتدای سشن", overlay: ["level"], rr: 1.8 },
  ict_ods: { fa: "ورود با ODS (Open Driven Session) هم‌سو با جهت باز", overlay: ["level"], rr: 1.8 },
  vol_spike: { fa: "ورود با اسپایک حجم در جهت حرکت", overlay: ["volume"], rr: 2 },
  vol_obv: { fa: "ورود با واگرام OBV نسبت به قیمت", overlay: ["obv"], rr: 2 },
  vol_vwap: { fa: "ورود هم‌سو با VWAP و حجم بالا", overlay: ["vwap"], rr: 2 },
  vol_accum: { fa: "ورود با الگوی Accumulation/Distribution", overlay: ["adl"], rr: 1.8 },
  vol_effort: { fa: "ورود با تأیید تلاش در برابر نتیجه", overlay: ["volume"], rr: 2 },
  vol_cvd: { fa: "ورود با واگرام CVD (حجم تجمعی تفاضلی)", overlay: ["cvd"], rr: 2 },
  vola_atr: { fa: "ورود با برگشت ATR از سطح افراطی", overlay: ["atr"], rr: 1.8 },
  vola_bbsqueeze: { fa: "ورود با شکست Squeeze بولینجر", overlay: ["bollinger"], rr: 2.2 },
  vola_keltner: { fa: "ورود با اسکویز و گسترش کانال کلتنر", overlay: ["keltner"], rr: 2 },
  vola_expansion: { fa: "ورود با گسترش ناگهانی ATR و دنبال‌کردن حرکت", overlay: ["atr"], rr: 2 },
  vola_range: { fa: "ورود پیش از شکست پس از فشرده‌شدن محدوده", overlay: ["range"], rr: 1.8 },
  vola_funnel: { fa: "ورود با فشرده‌شدن تدریجی نوسان (Funnel)", overlay: ["atr"], rr: 2 },
  sr_levels: { fa: "ورود با تماس سطح حمایتی/مقاومتی قوی", overlay: ["level"], rr: 2 },
  sr_pivot: { fa: "ورود با واکنش به پیوت روزانه", overlay: ["pivot"], rr: 1.8 },
  sr_fib: { fa: "ورود با ریتریس‌شدن فیبوناچی (۳۸.۲–۶۱.۸)", overlay: ["fib"], rr: 2 },
  sr_round: { fa: "ورود با برخورد به عدد گرد", overlay: ["round"], rr: 1.2 },
  sr_trendline: { fa: "ورود با ربانی از روندکشی (Trendline)", overlay: ["trendline"], rr: 2 },
  sr_conger: { fa: "ورود با هم‌راستایی چند سطح (Confluent Levels)", overlay: ["level"], rr: 2 },
  sr_magnet: { fa: "ورود با جذب به سطح پرحجم (S/R Magnet)", overlay: ["level"], rr: 1.5 },
  mtf_confluence: { fa: "ورود با همسویی چند تایم‌فریم", overlay: ["mtf"], rr: 2 },
  mtf_highertf: { fa: "ورود هم‌سو با روند تایم‌فریم بالاتر", overlay: ["mtf"], rr: 2 },
  mtf_filter: { fa: "ورود با فیلتر روند تایم‌فریم بالاتر", overlay: ["mtf"], rr: 2 },
  mtf_t1: { fa: "ورود روی تایم‌فریم ترید با تأیید HTF", overlay: ["mtf"], rr: 1.8 },
  mtf_expansion: { fa: "ورود با گسترش روند بین تایم‌فریم‌ها", overlay: ["mtf"], rr: 2.5 },
  mtf_bias: { fa: "ورود فقط در جهت بایاس کلی روزانه", overlay: ["mtf"], rr: 2 },
  struct_bos: { fa: "ورود با Break of Structure در جهت روند", overlay: ["bos"], rr: 2 },
  struct_choch: { fa: "ورود با Change of Character", overlay: ["choch"], rr: 1.8 },
  struct_mss: { fa: "ورود با Market Structure Shift", overlay: ["mss"], rr: 2.2 },
  struct_continuation: { fa: "ورود با ادامه روند ساختار (سهم برابر)", overlay: ["structure"], rr: 2.5 },
  struct_reversal: { fa: "ورود با برگشت ساختار major", overlay: ["structure"], rr: 2.5 },
  struct_invalid: { fa: "ورود با ابطال ساختار قبلی و پترن جدید", overlay: ["structure"], rr: 1.5 },
  liq_sweep: { fa: "ورود پس از برداشت نقدینگی (Sweep)", overlay: ["liquidity"], rr: 2.5 },
  liq_session: { fa: "ورود با احترام به سطح سشن قبلی", overlay: ["session"], rr: 2 },
  liq_weekend: { fa: "ورود با پرشدن گپ آخر هفته", overlay: ["gap"], rr: 1.2 },
  liq_poi: { fa: "ورود از POI سفارشی نقدینگی", overlay: ["poi"], rr: 2.2 },
  liq_run: { fa: "ورود در جهت حرکت نقدینگی (Liquidity Run)", overlay: ["liquidity"], rr: 2 },
  liq_absorb: { fa: "ورود با جذب سفارش‌ها در سطح", overlay: ["liquidity"], rr: 1.8 },
  combo_ema_rsi: { fa: "ورود با EMA روند + تأیید RSI", overlay: ["ema", "rsi"], rr: 2 },
  combo_macd_bb: { fa: "ورود با MACD + باند بولینجر", overlay: ["macd", "bollinger"], rr: 2 },
  combo_smt: { fa: "ورود با واگرام بین جفت‌ارزها (SMT)", overlay: [], rr: 2 },
  combo_trio: { fa: "ورود با ترکیب سه فیلتر (EMA+RSI+MACD)", overlay: ["ema", "rsi", "macd"], rr: 2 },
  combo_wolf: { fa: "ترکیب اختصاصی WOLF: ساختار + نقدینگی + واگرایی", overlay: ["structure", "liquidity"], rr: 3 },
  combo_fisher: { fa: "ورود با برگشت Fisher Transform", overlay: ["fisher"], rr: 1.8 },
  combo_magic: { fa: "ورود با ترکیب شاخص‌های کلاسیک (Magic)", overlay: ["ema", "rsi"], rr: 2 },
  combo_supres: { fa: "ورود با ترکیب حمایت/مقاومت و حجم", overlay: ["level", "volume"], rr: 2 },
};

// Category names
export const CAT_FA: Record<string, string> = {
  price_action: "پرایس اکشن",
  chart_patterns: "الگوهای نموداری",
  trend_following: "پیروی از روند",
  momentum: "مومنتوم",
  mean_reversion: "بازگشت به میانگین",
  breakout: "بریک‌اوت",
  scalping: "اسکالپینگ",
  swing: "سوینگ",
  smc: "اس‌ام‌سی (SMC)",
  ict: "آی‌سی‌تی (ICT)",
  volume: "حجم",
  volatility: "نوسان‌پذیری",
  support_resistance: "حمایت و مقاومت",
  multi_timeframe: "چند تایم‌فریم",
  market_structure: "ساختار بازار",
  liquidity: "نقدینگی",
  indicator_combos: "ترکیب اندیکاتورها",
};

// seed rows: [family, key, nameEn, nameFa, category, market, timeframes, weight]
type Seed = [string, string, string, string, string, string, string, number];

export const STRATEGY_SEEDS: Seed[] = [
  // ── Price Action (پرایس اکشن) ────────────────────────────────────────
  ["pa_pinbar", "pa_pinbar", "Pin Bar Reversal", "پین‌بار برگشتی", "price_action", "all", "15m,30m,1h,4h", 1.0],
  ["pa_engulfing", "pa_engulfing", "Engulfing Pattern", "شمع انگالفینگ", "price_action", "all", "15m,30m,1h,4h", 0.95],
  ["pa_inside", "pa_inside", "Inside Bar Breakout", "شکست نبرد داخل", "price_action", "all", "5m,15m,30m,1h", 0.9],
  ["pa_fakey", "pa_fakey", "Fakey (Fake Break)", "فیکی (شکست جعلی)", "price_action", "all", "15m,30m,1h,4h", 0.9],
  ["pa_hammershooting", "pa_hammershooting", "Hammer / Shooting Star", "چکش / ستاره دنباله‌دار", "price_action", "all", "30m,1h,4h", 0.85],
  ["pa_doji", "pa_doji", "Doji Reversal", "داوجی برگشتی", "price_action", "all", "1h,4h", 0.8],
  ["pa_threeb", "pa_threeb", "Three Bar Reversal", "الگوی سه‌شمع", "price_action", "all", "15m,30m,1h", 0.85],
  // ── Chart Patterns (الگوهای نمودار) ─────────────────────────────────
  ["pat_double", "pat_double", "Double Top / Bottom", "سقف/کف دو قله", "chart_patterns", "all", "1h,4h,1d", 0.9],
  ["pat_headshoulder", "pat_headshoulder", "Head & Shoulders", "سر و شانه", "chart_patterns", "all", "4h,1d", 0.85],
  ["pat_triangle", "pat_triangle", "Triangle Breakout", "شکست مثلث", "chart_patterns", "all", "30m,1h,4h", 0.85],
  ["pat_wedge", "pat_wedge", "Wedge Reversal", "گاوه برگشتی", "chart_patterns", "all", "1h,4h", 0.85],
  ["pat_rectangle", "pat_rectangle", "Rectangle Range", "محدوده مستطیل", "chart_patterns", "all", "15m,30m,1h,4h", 0.8],
  ["pat_flag", "pat_flag", "Flag / Pennant", "پرچم / پینانت", "chart_patterns", "all", "15m,30m,1h", 0.85],
  ["pat_cup", "pat_cup", "Cup & Handle", "جام و دسته", "chart_patterns", "all", "4h,1d", 0.8],
  // ── Trend Following (پیروی از روند) ───────────────────────────────────────
  ["trend_ema", "trend_ema", "EMA Pullback", "پولبک به EMA", "trend_following", "all", "15m,30m,1h,4h", 1.0],
  ["trend_cross", "trend_cross", "EMA Crossover", "تقاطع EMA", "trend_following", "all", "1h,4h", 0.95],
  ["trend_macd", "trend_macd", "MACD Trend Follow", "MACD دنبال‌کننده روند", "trend_following", "all", "30m,1h,4h", 0.9],
  ["trend_supertrend", "trend_supertrend", "SuperTrend Follow", "سوپرترند", "trend_following", "all", "5m,15m,30m,1h,4h", 0.9],
  ["trend_adx", "trend_adx", "ADX Trend Strength", "قدرت روند ADX", "trend_following", "all", "1h,4h", 0.85],
  ["trend_psar", "trend_psar", "Parabolic SAR", "پارابولیک سار", "trend_following", "all", "15m,30m,1h", 0.85],
  ["trend_channel", "trend_channel", "Trend Channel", "کانال روند", "trend_following", "all", "30m,1h,4h", 0.85],
  // ── Momentum (مومنتوم) ─────────────────────────────────────────────────────
  ["mom_rsi", "mom_rsi", "RSI Momentum", "مومنتوم RSI", "momentum", "all", "15m,30m,1h", 0.9],
  ["mom_stoch", "mom_stoch", "Stochastic Cross", "تقاطع استوکاستیک", "momentum", "all", "5m,15m,30m,1h", 0.85],
  ["mom_macdhist", "mom_macdhist", "MACD Histogram", "هیستوگرام MACD", "momentum", "all", "15m,30m,1h", 0.85],
  ["mom_roc", "mom_roc", "Rate of Change", "نرخ تغییر ROC", "momentum", "all", "30m,1h", 0.8],
  ["mom_cci", "mom_cci", "CCI Momentum", "مومنتوم CCI", "momentum", "all", "15m,30m,1h", 0.8],
  ["mom_williams", "mom_williams", "Williams %R", "ویلیامز %R", "momentum", "all", "15m,30m", 0.8],
  // ── Mean Reversion (بازگشت به میانگین) ────────────────────────────────────
  ["meanr_bb", "meanr_bb", "Bollinger Reversion", "بازگشت بولینجر", "mean_reversion", "all", "15m,30m,1h", 0.9],
  ["meanr_rsi2", "meanr_rsi2", "RSI(2) Reversion", "بازگشت RSI(2)", "mean_reversion", "all", "5m,15m", 0.9],
  ["meanr_zscore", "meanr_zscore", "Z-Score Reversal", "بازگشت Z-Score", "mean_reversion", "all", "30m,1h", 0.85],
  ["meanr_keltner", "meanr_keltner", "Keltner Reversion", "بازگشت کلتنر", "mean_reversion", "all", "15m,30m", 0.8],
  ["meanr_gaps", "meanr_gaps", "Gap Fill", "پرشدن گپ", "mean_reversion", "forex", "1h,4h", 0.75],
  // ── Breakout (بریک‌اوت) ────────────────────────────────────────────────────
  ["brk_consolidation", "brk_consolidation", "Consolidation Breakout", "شکست تثبیت", "breakout", "all", "15m,30m,1h", 0.95],
  ["brk_donchian", "brk_donchian", "Donchian Breakout", "شکست دونچیان", "breakout", "all", "1h,4h,1d", 0.9],
  ["brk_range", "brk_range", "Opening Range Breakout", "شکست بازه افتتاحیه", "breakout", "forex", "5m,15m,30m", 0.85],
  ["brk_level", "brk_level", "Level Breakout", "شکست سطح", "breakout", "all", "15m,30m,1h", 0.95],
  ["brk_volatility", "brk_volatility", "Volatility Breakout", "شکست نوسانی", "breakout", "all", "15m,30m,1h", 0.85],
  ["brk_move", "brk_move", "Breakaway Move", "حرکت شکستی", "breakout", "all", "5m,15m", 0.8],
  // ── Scalping (اسکالپینگ) ──────────────────────────────────────────────────
  ["scalp_snr", "scalp_snr", "S/R Scalp", "اسکالپ حمایت/مقاومت", "scalping", "forex", "1m,5m,15m", 0.9],
  ["scalp_1m", "scalp_1m", "1-Minute Scalp", "اسکالپ یک‌دقیقه‌ای", "scalping", "forex", "1m,5m", 0.85],
  ["scalp_vwap", "scalp_vwap", "VWAP Scalp", "اسکالپ VWAP", "scalping", "forex", "5m,15m", 0.85],
  ["scalp_momentum", "scalp_momentum", "Momentum Scalp", "اسکالپ مومنتوم", "scalping", "forex", "1m,5m", 0.8],
  // ── Swing (سوینگ) ──────────────────────────────────────────────────────────
  ["swing_retest", "swing_retest", "Boom & Retest", "شکست و ری‌تست", "swing", "all", "30m,1h,4h", 1.0],
  ["swing_aroon", "swing_aroon", "Aroon Swing", "سوینگ آرون", "swing", "all", "1h,4h", 0.8],
  ["swing_harami", "swing_harami", "Harami Reversal", "هارامی", "swing", "all", "30m,1h", 0.8],
  ["swing_pullback", "swing_pullback", "Trend / Pullback", "پولبک روند", "swing", "all", "1h,4h", 0.9],
  // ── SMC ────────────────────────────────────────────────────────────────
  ["smc_ob", "smc_ob", "Order Block Entry", "ورود اردر بلاک", "smc", "all", "15m,30m,1h,4h", 1.0],
  ["smc_fvg", "smc_fvg", "FVG (Fair Value Gap)", "فیر ولیو گیپ", "smc", "all", "15m,30m,1h", 0.95],
  ["smc_liquidity", "smc_liquidity", "Liquidity Sweep", "سویپ نقدینگی", "smc", "all", "15m,30m,1h", 0.95],
  ["smc_mitigation", "smc_mitigation", "Mitigation Entry", "میتریگیشن", "smc", "all", "30m,1h", 0.9],
  ["smc_imbalance", "smc_imbalance", "Imbalance Trade", "ایمبالانس", "smc", "all", "15m,30m", 0.85],
  ["smc_breaker", "smc_breaker", "Breaker Block", "بریکر بلاک", "smc", "all", "30m,1h,4h", 0.85],
  // ── ICT ──────────────────────────────────────────────────────────────────
  ["ict_killzone", "ict_killzone", "Killzone Entry", "کیل‌زون", "ict", "all", "5m,15m,30m", 0.9],
  ["ict_opening", "ict_opening", "Opening Range (OR)", "بازه افتتاحیه", "ict", "all", "5m,15m", 0.85],
  ["ict_ote", "ict_ote", "Optimal Trade Entry (OTE)", "OTE", "ict", "all", "15m,30m", 0.9],
  ["ict_silverbullet", "ict_silverbullet", "Silver Bullet", "سولور بولت", "ict", "forex", "5m,15m", 0.9],
  ["ict_power3", "ict_power3", "Power of Three", "پاور ۳", "ict", "all", "15m,30m", 0.8],
  ["ict_smart", "ict_smart", "Smart Money Trap", "تله پول هوشمند", "ict", "all", "1h,4h", 0.8],
  ["ict_judas", "ict_judas", "Judas Swing", "جوداس سوینگ", "ict", "forex", "5m,15m", 0.8],
  ["ict_ods", "ict_ods", "Open Driven Session (ODS)", "ODS", "ict", "forex", "30m", 0.75],
  // ── Volume (حجم) ──────────────────────────────────────────────────────────
  ["vol_spike", "vol_spike", "Volume Spike", "اسپایک حجم", "volume", "all", "5m,15m", 0.85],
  ["vol_obv", "vol_obv", "OBV Trend", "روند OBV", "volume", "all", "15m,30m,1h", 0.8],
  ["vol_vwap", "vol_vwap", "VWAP Trend", "روند VWAP", "volume", "all", "5m,15m,30m", 0.85],
  ["vol_accum", "vol_accum", "Acc / Dist", "انباشت/توزیع", "volume", "all", "30m,1h", 0.75],
  ["vol_effort", "vol_effort", "Effort vs Result", "تلاش در برابر نتیجه", "volume", "all", "15m,30m", 0.8],
  ["vol_cvd", "vol_cvd", "CVD Divergence", "واگرایی CVD", "volume", "all", "5m,15m", 0.8],
  // ── Volatility (نوسان‌پذیری) ──────────────────────────────────────────────
  ["vola_atr", "vola_atr", "ATR Reversal", "برگشت ATR", "volatility", "all", "15m,30m", 0.8],
  ["vola_bbsqueeze", "vola_bbsqueeze", "Bollinger Squeeze", "اسکویز بولینجر", "volatility", "all", "15m,30m,1h", 0.9],
  ["vola_keltner", "vola_keltner", "Keltner Squeeze", "اسکویز کلتنر", "volatility", "all", "15m,30m", 0.85],
  ["vola_expansion", "vola_expansion", "Vol Expansion", "گسترش نوسان", "volatility", "all", "5m,15m", 0.85],
  ["vola_range", "vola_range", "Range Compression", "فشردگی محدوده", "volatility", "all", "15m,30m", 0.8],
  ["vola_funnel", "vola_funnel", "Volatility Funnel", "قیف نوسان", "volatility", "all", "15m,30m", 0.75],
  // ── Support/Resistance (حمایت و مقاومت) ───────────────────────────────────
  ["sr_levels", "sr_levels", "Level Bounce", "رباند از سطح", "support_resistance", "all", "30m,1h,4h", 1.0],
  ["sr_pivot", "sr_pivot", "Daily Pivot", "پیوت روزانه", "support_resistance", "all", "30m,1h", 0.85],
  ["sr_fib", "sr_fib", "Fibonacci Retracement", "فیبوناچی", "support_resistance", "all", "1h,4h", 0.85],
  ["sr_round", "sr_round", "Round Numbers", "اعداد گرد", "support_resistance", "all", "5m,15m,30m", 0.75],
  ["sr_trendline", "sr_trendline", "Trendline Bounce", "رباند از خط روند", "support_resistance", "all", "30m,1h,4h", 0.9],
  ["sr_conger", "sr_conger", "Confluent Levels", "سطح‌های هم‌راستا", "support_resistance", "all", "30m,1h", 0.8],
  ["sr_magnet", "sr_magnet", "S/R Magnet", "آهنربای سطح", "support_resistance", "all", "15m,30m", 0.75],
  // ── Multi-Timeframe (چند تایم‌فریم) ───────────────────────────────────────
  ["mtf_confluence", "mtf_confluence", "MTF Confluence", "همسویی چند TF", "multi_timeframe", "all", "15m,30m,1h,4h", 1.0],
  ["mtf_highertf", "mtf_highertf", "Higher-TF Trend", "روند تایم‌فریم بالا", "multi_timeframe", "all", "30m,1h,4h", 0.9],
  ["mtf_filter", "mtf_filter", "HTF Filter", "فیلتر HTF", "multi_timeframe", "all", "15m,30m,1h", 0.85],
  ["mtf_t1", "mtf_t1", "T1 Execution", "اجرا روی TF پایه", "multi_timeframe", "all", "5m,15m,30m", 0.85],
  ["mtf_expansion", "mtf_expansion", "MTF Expansion", "گسترش بین TFها", "multi_timeframe", "all", "30m,1h,4h", 0.8],
  ["mtf_bias", "mtf_bias", "Daily Bias", "بایاس روزانه", "multi_timeframe", "all", "1h,4h,1d", 0.85],
  // ── Market Structure (ساختار بازار) ───────────────────────────────────────
  ["struct_bos", "struct_bos", "Break of Structure", "شکست ساختار", "market_structure", "all", "15m,30m,1h", 0.95],
  ["struct_choch", "struct_choch", "Change of Character", "تغییر شخصیت", "market_structure", "all", "15m,30m", 0.9],
  ["struct_mss", "struct_mss", "Market Structure Shift", "جابجایی ساختار", "market_structure", "all", "15m,30m,1h", 0.9],
  ["struct_continuation", "struct_continuation", "Structure Continue", "ادامه ساختار", "market_structure", "all", "30m,1h", 0.9],
  ["struct_reversal", "struct_reversal", "Structure Reversal", "برگشت ساختار", "market_structure", "all", "1h,4h", 0.85],
  ["struct_invalid", "struct_invalid", "Invalidation Trade", "معامله ابطال", "market_structure", "all", "15m,30m", 0.75],
  // ── Liquidity (نقدینگی) ───────────────────────────────────────────────────
  ["liq_sweep", "liq_sweep", "Liquidity Sweep", "سویپ نقدینگی", "liquidity", "all", "15m,30m,1h", 0.95],
  ["liq_session", "liq_session", "Session High/Low", "سقف/کف سشن", "liquidity", "all", "30m,1h", 0.85],
  ["liq_weekend", "liq_weekend", "Weekend Gap", "گپ آخر هفته", "liquidity", "forex", "4h,1d", 0.7],
  ["liq_poi", "liq_poi", "POI Liquidity", "نقطه POI", "liquidity", "all", "15m,30m,1h", 0.9],
  ["liq_run", "liq_run", "Liquidity Run", "حرکت نقدینگی", "liquidity", "all", "5m,15m,30m", 0.85],
  ["liq_absorb", "liq_absorb", "Absorption Entry", "ورود جذب سفارش", "liquidity", "all", "15m,30m", 0.8],
  // ── Indicator Combinations (ترکیب اندیکاتورها) ────────────────────────────
  ["combo_ema_rsi", "combo_ema_rsi", "EMA + RSI", "EMA + RSI", "indicator_combos", "all", "15m,30m,1h", 0.95],
  ["combo_macd_bb", "combo_macd_bb", "MACD + Bollinger", "MACD + بولینجر", "indicator_combos", "all", "30m,1h", 0.9],
  ["combo_smt", "combo_smt", "Smart Money Technique", "تکنیک اس ام تی", "indicator_combos", "all", "15m,30m,1h", 0.85],
  ["combo_trio", "combo_trio", "Triple Filter", "فیلتر سه‌گانه", "indicator_combos", "all", "30m,1h", 0.9],
  ["combo_wolf", "combo_wolf", "Wolf Confluence", "ترکیب اختصاصی ول", "indicator_combos", "all", "15m,30m,1h,4h", 1.0],
  ["combo_fisher", "combo_fisher", "Fisher Transform", "فیشر ترنسفورم", "indicator_combos", "all", "15m,30m", 0.85],
  ["combo_magic", "combo_magic", "Magic Indicator", "اندیکاتور جادویی ESR", "indicator_combos", "all", "5m,15m,30m", 0.8],
  ["combo_supres", "combo_supres", "S/R + Volume", "S/R + حجم", "indicator_combos", "all", "30m,1h", 0.9],
];

export const CATEGORY_IDS = [
  "price_action",
  "chart_patterns",
  "trend_following",
  "momentum",
  "mean_reversion",
  "breakout",
  "scalping",
  "swing",
  "smc",
  "ict",
  "volume",
  "volatility",
  "support_resistance",
  "multi_timeframe",
  "market_structure",
  "liquidity",
  "indicator_combos",
];